#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -f log.blockMesh
rm -f log.setFields
rm -f log.interFoam

pyFoamClearCase.py interfoam_case/
#------------------------------------------------------------------------------
