#!/bin/sh
#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -f log.blockMesh

runApplication blockMesh -case interfoam_case
#------------------------------------------------------------------------------
